name: Test and Build

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  ci-tests:
    name: CI tests
    uses: glenn20/python-ci/.github/workflows/_ci_tests.yaml@main
    with:
      os: '["ubuntu-latest"]'
      python-version: '["3.9", "3.11"]'
    permissions:
      id-token: none

  publish-test:
    name: Publish to test.pypi
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/publish.yaml
    with:
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!
